### ISSUE TITLE
[BUG] Lua lsp doesn't install

### ISSUE THREAD

**Issue by Jakemate977** [NTBBloodbath/doom-nvim#295]
### Current Behavior:

The sumneko_lua lsp fails to install.
Output of :LspInstallInfo:
![image](https://user-images.githubusercontent.com/68245655/150695956-67960197-b02f-4496-8815-b93e45cb6280.png)

### Expected Behavior:

sumneko_lua installs.

### Steps To Reproduce:
1. Enable the +lsp flag of lua.

### Anything else:

The issue is [already fixed](https://github.com/williamboman/nvim-lsp-installer/blob/2c80c2ffbfd28e1e2eec4993ba6aea411a0a52d6/lua/nvim-lsp-installer/servers/sumneko_lua/init.lua#L19) in nvim-lsp-installer but since the packer dependency is pinned it is using a version that doesn't have the fix.

**Comment by connorgmeehan** [comment]
Pinning commits, damned if you do damned, if you dont :(.  This is a tough one because nvim-lsp-installer has dropped 0.5 support entirely.  I was hoping to do it when the module architecture released but should we just drop 0.5 support now @NTBBloodbath?

**Comment by NTBBloodbath** [comment]
Hey, I was thinking about dropping 0.5 after releasing the new incoming version but it seems that we will need to drop it asap. I'm totally fine with this decision, we could make a new release with the current development branch that has changes for 0.6 _and 0.6.1_ lsp changes and such stuff and update lsp-installer on it.

**Comment by Jakemate977** [comment]
Totally unrelated question, but what is the difference between the develop and next branch?

**Comment by connorgmeehan** [comment]
Just to update you, we've fixed this on the develop branch and will be pushing a release to main soon (breaks 0.5 compatibility).  Feel free to use develop if you'd like.

Regarding your question, we're currently re-writing a lot of the doom-nvim to make configuration more concise and make everything more modular and easier to maintain/contribute.  There's a very large PR that we're still working on which is why there's not much of a difference between the two branches.

**Comment by Jakemate977** [comment]
Ok, Thanks!

**Comment by connorgmeehan** [comment]
Hey just to let you know this has been resolved.  There's a new release (v3.3.0) that you can pull that includes updated versions of everything.  We've ended up just dropping 0.5 compatibility.  Let me know if you have any issues!

**Comment by Jakemate977** [comment]
Not sure if intentional, but you forgot to update the readme, anyways, thanks for your help
