### ISSUE TITLE
[BUG][next] Disabling external clipboard isn't working anymore

### ISSUE THREAD

**Issue by baurmatt** [NTBBloodbath/doom-nvim#361]
### Current Behavior:
Next doesn't support disabling the external clipboard anymore

### Expected Behavior:
```
    -- Use clipboard outside of vim
    -- false : won't use third party clipboard
    -- true  : enables third part clipboard
    -- @default = true
    clipboard = true,
 ```
-> Works :)

### Logs

<details>
<summary>Check Health Output</summary>

</details>

<details>
<summary>Doom Report Output</summary>

</details>

**Comment by connorgmeehan** [comment]
This has been fixed in https://github.com/NTBBloodbath/doom-nvim/commit/d0ab69e8b9ce8b2a324b4730a26b6eb9783d6149 :)

**Comment by baurmatt** [comment]
Thanks for all the fixes! :) This is the only one which I can't get to work. I've updated the code like this:

```bash
cd ~/.config/nvim
git stash
git fetch
git rebase origin/next
git stash pop
```

But afterwards `doom.clipboard = false` still doesn't work 🤔
